/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_printf_arrayC.c                                 :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: obelange <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2016/09/30 14:48:00 by obelange          #+#    #+#             */
/*   Updated: 2016/09/30 14:48:00 by obelange         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libftprintf.h"

void	(*g_printf_get[90]) (t_mod *conv, va_list args) = {
	ft_printf_get_percent,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	ft_printf_get_c,
	ft_printf_get_cap_d,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	ft_printf_get_cap_o,
	0,
	0,
	0,
	ft_printf_get_cap_s,
	0,
	ft_printf_get_cap_u,
	0,
	0,
	ft_printf_get_cap_x,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	ft_printf_get_b,
	ft_printf_get_c,
	ft_printf_get_d,
	0,
	0,
	0,
	0,
	ft_printf_get_i,
	0,
	0,
	0,
	0,
	0,
	ft_printf_get_o,
	ft_printf_get_p,
	0,
	0,
	ft_printf_get_s,
	0,
	ft_printf_get_u,
	0,
	0,
	ft_printf_get_x,
	0,
	0,
	0,
	0,
	0,
	0
};
